### ISSUE TITLE
Problems with Collections with dash in the name

### ISSUE THREAD

**Issue by mreinerth** [coderofsalvation/dpd-acl-roles-permissions#1]
My server crashes when i use this package after create a collection with dash (-) in the name.

the crash happen in line 89 of  your index.js.  
var resourceConfig = ctx.dpd[ resourceName ].getResource().config .

Get TypeError: Cannot read Property 'getResource' of undefined.

You need to remove the dash from resourcName  in  getResourceNameFromUrl or use dpd as a function:

Reference:
[http://docs.deployd.com/docs/collections/reference/dpd-js.html](http://docs.deployd.com/docs/collections/reference/dpd-js.html)

Note: If your Collection name has a dash in it (e.g. /todo-lists), the dash is removed when accessing it in this way (e.g. dpd.todolists).

You can also access your collection by using dpd(collectionName) as a function.

Examples:
dpd('todos')
dpd('users')
dpd('todo-lists')      -> here it workes with the dash in it

Thanks

**Comment by coderofsalvation** [comment]
ok i'll test this and get back to you th

**Comment by coderofsalvation** [comment]
reproduced, fixed, tested, commited, and published: 1.2.5 -> 1.2.6

Thank you very much for this issue.

Cheers
